use sakila;

##Capitulo 7 

SET @NOMBRE = "PLEASE FIND THE SUBSTRING IN THIS STRING"

## PREGUNTA 1 
## ENCONTRAR LOS CARACTERES DEL 17 AL 25 DEL STRING ANTERIOR

SELECT
	SUBSTRING(@NOMBRE,25,17)
AS EJERCICIO_1;

## PREGUNTA 2
## ESCRIBIR UNA QUERY QUE ENTREGUE EL VALOR ABSOLUTO DE (-1,0,1) DEL NUMERO -25.76823 Y QUE LO RETORNE REDONDEADO A LA SIGUIENTE CENTENA

SET @NUMERO = -25.76823

SELECT
	CASE
		WHEN @NUMERO > 0 THEN 1
        WHEN @NUMERO < 0 THEN -1
        ELSE 0
	END AS ABS_VALUE,
    ROUND(@NUMERO,3)
AS EJERCICIO_2;

